### PR TITLE
Bug: Text was duplicating it for all users

### PR DESCRIPTION
**Pull request by xbdmHQ**
I accidentally deleted the fork repo not knowing it will delete the pull request lol.

Old one: https://github.com/diced/zipline/pull/377

### CODE REVIEW

**Comment by diced** [comment]
The commit and PR title seems like it has nothing to do with the actual contents of this PR? If it was a mistake just change the title, if it was not could you explain what it means?

**Comment by er9ugi9uier9** [comment]
When you make a text file by default, it names it regularly without randomizing it and all it overwrites all users text files

**Comment by TacticalTechJay** [comment]
When you say "make a text file", are you referring to using the dashboard's upload to text or zipline's api upload with a text file?

**Comment by xbdmHQ** [comment]
uploading by dashboard

**Comment by TacticalTechJay** [comment]
This seems as though it would be more of a configuration issue rather than a bug. Try checking if you have [`UPLOADER_DEFAULT_FORMAT`](https://zipline.diced.tech/docs/config/uploader#uploader_default_format) set somewhere when starting zipline. If you are certain this is a bug you're fixing, provide us some reproducible steps.

**Pull request closed without merging**
